### ISSUE TITLE
Attachment

### ISSUE THREAD

**Issue by arth1992** [blondishnet/PHPads#4]
Hello
Whenever i try to create add i am not able to add/attach image directly to the description i had to copy paste link to the image in link textarea. So what is the use of file upload when you can attach it directly to the ads.
It is a nice application. Thanks for sharing

**Comment by blondishnet** [comment]
The attachment is a new feature that is being worked on that has been recently added.

**Comment by arth1992** [comment]
Is that feature has been updated or still remaining?

**Comment by PhilTanner** [comment]
Hi arth1992,

As of this second, the File upload script does just upload the file and output the URL to then enter into the image URL field during the "Add Ad" section, yes.

I am hoping to make this more user friendly and put it in all inline at the Add Ad point, and to adjust the File Upload to let you manage currently uploaded resources (at the moment it's deliberately set up to prevent overwriting).  This should be coming over the next month.

P

**Comment by arth1992** [comment]
Hello,

Thanks for replying. Hoping to see that change soon.
